apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
     name: myapp-pod
spec:
  containers:
    - name: myapp-containers
      image: busybox:1.28
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: app-cm
              key: firstname
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']



