apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
    tier: backend
    type: web
  name: redis
  namespace: default
  resourceVersion: "68270"
  uid: c82d0caf-7389-4b6f-adb1-293bd1951a27
spec:
  containers:
  - image: redis
    name: redis-container
   