apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    tier: frontend
    type: web
  name: nginx
  namespace: default
  resourceVersion: "68270"
  uid: c82d0caf-7389-4b6f-adb1-293bd1951a27
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: cka-simoncluster-multi-node2-worker
   